server:
  port: 8080
  servlet:
    context-path: /test/api

spring:
  application:
    name: auth-api
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: master
  jpa:
    hibernate:
      ddl-auto: validate
      use-new-id-generator-mappings: true
    show-sql: true
    properties:
      hibernate.format_sql: true

logging:
  file:
    name: ./logs/test-api.log
    path: ./logs
    max-history: 10
    max-size: 10MB
  level:
    root: info